all:
  vars:
    control_plane_endpoint: 192.168.1.100
    load_balancer_ip_pool:
      - 192.168.1.224/27
metal:
  children:
    masters:
      hosts:
        naus0: {ansible_host: 192.168.1.110, mac: '54:bf:64:a0:4b:29', disk: sda, network_interface: eno1}
    #workers:
    #  hosts:
    #    metal3: {ansible_host: 192.168.1.113, mac: '00:23:24:d1:f4:d6', disk: sda, network_interface: eno1}
